export const GET_DATA_POST_REQUEST = 'GET_DATA_POST_REQUEST';
export const GET_DATA_POST_SUCCESS = 'GET_DATA_POST_SUCCESS';
export const GET_DATA_POST_ERROR = 'GET_DATA_POST_ERROR';
//
export const CLEAR_DATA_POST = 'CLEAR_DATA_POST';
