export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
export const REMOVE_ALL_NOTIFICATIONS = 'REMOVE_ALL_NOTIFICATIONS';
// type
export const NOTIFICATION_TYPE_SUCCESS = 'Success';
export const NOTIFICATION_TYPE_WARNING = 'Warning';
export const NOTIFICATION_TYPE_INFO = 'Info';
export const NOTIFICATION_TYPE_ERROR = 'Error';
